### PR TITLE
release artifacts

### PR DESCRIPTION
**Pull request by InoMurko**
Publish alpine:3.11 barebon release as cirleci artifact.

### CODE REVIEW

**Comment by InoMurko** [comment]
https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/7400/workflows/c68f52aa-b585-45b0-9cdc-abb5ebad3406/jobs/66207/artifacts

https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/7399/workflows/7201bede-23f4-4f42-82d6-cac8ed62bb20/jobs/66189/artifacts

**Comment by unnawut** [comment]
Oh this is nice. Might also be able to automate the release entirely as well: https://developer.github.com/v3/repos/releases

**Comment by unnawut** [comment]
Not sure why in https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/7399/workflows/7201bede-23f4-4f42-82d6-cac8ed62bb20/jobs/66189/artifacts the directory name looks off:

```
$WATCHER_IMAGE_NAME/md5
$WATCHER_IMAGE_NAME/watcher-1.0.0+aa4582a.tar.gz
```

**Comment by InoMurko** [comment]
> https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/7399/workflows/7201bede-23f4-4f42-82d6-cac8ed62bb20/jobs/66189/artifacts

Aha, that was one of my previous commits. I thought I would be able to put the release name in the path, but env vars are not evaludated in those steps.

**Comment by unnawut** [comment]
Ah ok I see you had to manually enable publish_watcher_info to test that it works 👌

**Comment by InoMurko** [comment]
> Ah ok I see you had to manually enable publish_watcher_info to test that it works 👌

yeah had to see if it works

**Comment by unnawut** [comment]
@boolafish Can you have a review of this? Will be nice to have it merged so we can make the release content more helpful for users

**Pull request merged**
