### PR TITLE
Auto PR with Auto merge for syncing master-v2

### PR DESCRIPTION
**Pull request by souradeep-das**
### Overview

Create/modify a PR and auto-merge to sync master-v2 with changes pushed to master  

### Flow

<ul>
<li>Opens a pull request (`master` -> `master-v2` when changes are pushed to master</li>
<li>If there is no merge conflicts</li>
<ol>
<li>Auto attach the label `sync master-v2` to the PR</li>
<li>Auto Merge the PR</li>
</ol>
<li>If there are merge conflicts</li>
<ol>
<li>Fix conflicts manually</li>
<li>Auto attaches label `sync master-v2` to the PR</li>
<li>Manually merge the PR</li>
</ul>
</ol>

### Additional settings

1. Please add omisego-bot's token under the name `HOUSE_KEEPER_BOT_TOKEN`
2. We probably **need to do away** with some branch rules for `master-v2` to easily auto-merge
    1. require pull request reviews for master-v2
    2. require status checks to pass before merging. ( since it just reflects the `master` branch, waiting introduces complications :( )

### CODE REVIEW

**Comment by InoMurko** [comment]
is there a way to auto-merge PR if there are not conflicts?

**Comment by souradeep-das** [comment]
@InoMurko Interesting! Looks like this could do this https://developer.github.com/v3/pulls/#merge-a-pull-request

**Comment by InoMurko** [comment]
This should help us reduce steps and friction to the minimum!

**Comment by souradeep-das** [comment]
How are we planning to tackle merge conflicts (if they come up)? Should we have a `master`-`master-copy`-`master-v2` flow and make the auto PR's from `master-copy`->`master-v2`? @boolafish @InoMurko 
Also since we want an auto-merge, do we remove pull request reviews from master-v2 or maybe reduce it to one?

**Comment by souradeep-das** [comment]
Yeah totally. Branching out on conflicts should work.

**Comment by boolafish** [comment]
> remove pull request reviews from master-v2 or maybe reduce it to one?

A trolling idea, we can have multiple bot approving 😂

**Comment by souradeep-das** [comment]
@boolafish added the auto-merge. Lmk if this is in order.

**Comment by souradeep-das** [comment]
Could we get a check if the settings have been applied before merge.

**Comment by InoMurko** [comment]
> Could we get a check if the settings have been applied before merge.

I'm perhaps out of the loop, what do you mean by that? Which settigs? master1->master2?

**Comment by souradeep-das** [comment]
@InoMurko mostly the branch restrictions and adding the access token for the omisego-bot. Redirecting to https://github.com/omgnetwork/elixir-omg/pull/1604#issue-439027142 under the additional settings section

**Comment by InoMurko** [comment]
> Please add omisego-bot's token under the name HOUSE_KEEPER_BOT_TOKEN
If I remember correctly, @unnawut you fixed a thing once for me so that comments were submitted with this bot. can you do ti here as well?

**Comment by souradeep-das** [comment]
Thanks 👍 , ohh so the bot's token is also added now?

**Comment by boolafish** [comment]
`HOUSE_KEEPER_BOT_TOKEN` added!

**Pull request merged**
