### PR TITLE
[Update]: swagger docs

### PR DESCRIPTION
**Pull request by dmitrydao**
## Overview

Watcher's Swagger docs update.

## Changes

Made the following changes to `info_api_specs.yaml` and `security_critical_api_specs.yaml` files:
- Updated company name and email.
- Added descriptions to the response body of `status.get` method.

### CODE REVIEW

**Comment by dmitrydao** [comment]
The watcher test has failed again. Maybe there are some specific checks that just have to be adjusted?

**Comment by unnawut** [comment]
The swagger specs is used to generate the cabbage test client. It's failing on:

```elixir
== Compilation error in file lib/client.ex ==
** (KeyError) key :end_datetime not found
    expanding struct: WatcherInfoAPI.Model.GetAllTransactionsBodySchema1.__struct__/1
    lib/client.ex:122: Itest.Client.get_transactions/1
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

@jarindr Can you have a look?

**Comment by jarindr** [comment]
> The swagger specs is used to generate the cabbage test client. It's failing on:
> 
> ```elixir
> == Compilation error in file lib/client.ex ==
> ** (KeyError) key :end_datetime not found
>     expanding struct: WatcherInfoAPI.Model.GetAllTransactionsBodySchema1.__struct__/1
>     lib/client.ex:122: Itest.Client.get_transactions/1
>     (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
> ```
> 
> @jarindr Can you have a look?

attempt to fix on here https://github.com/omgnetwork/elixir-omg/pull/1609 not sure why on many PR this doesn't happen 🔢

**Comment by dmitrydao** [comment]
@jarindr The Watcher test fails again. Is this a new normal?

**Pull request closed without merging**
