### PR TITLE
corrrectly serialize PIDs in alarms.get

### PR DESCRIPTION
**Pull request by ayrat555**
Fixes https://github.com/omgnetwork/elixir-omg/issues/1619

## Overview

Add Jason.Encoder for PID.

### CODE REVIEW

**Comment by InoMurko** [comment]
I would actually go down the route of setting the treshold to 1.0 so that the memory alarm never gets triggered (cc @unnawut). We report memory to Datadog and we can set our monitoring there. Wdyt @unnawut ?

**Comment by unnawut** [comment]
Hmm true I think this alarm is not needed for external consumption

**Comment by InoMurko** [comment]
cool. @ayrat555 if you could adapt this based on the comments it would be wonderful/better. thanks!

**Comment by ayrat555** [comment]
@InoMurko @unnawut done

**Comment by unnawut** [comment]
Amazing thanks 😂  Can you also set this alarm up in our monitoring tool as we merge this so we don't lose the alarm?

**Comment by ayrat555** [comment]
@unnawut what do you mean? I think this change will remove the alarm

**Comment by unnawut** [comment]
> @unnawut what do you mean? I think this change will remove the alarm

Ah Ino said it better than me prior 😂  "We report memory to Datadog and we can set our monitoring there."

**Comment by ayrat555** [comment]
@InoMurko @unnawut I don't think Datadog has the ability to monitor erlang processed

**Comment by unnawut** [comment]
> @InoMurko @unnawut I don't think Datadog has the ability to monitor erlang processes

Maybe https://github.com/ferd/vmstats that we have now? It taps into what erlang's memory module provides and already reporting to Datadog. There's `vmstats.memory.proc_used` and etc. but will need some digging into how to calculate for the alarm.

(I think this doesn't block merging of this PR though)

**Pull request merged**
